//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LFC10.rc
//
#define IDP_SOCKETS_INIT_FAILED         101
#define IDS_OPENCOMMERROR               102
#define IDC_EDGE_COLOR                  1001
#define FONT_COMBOBOX                   1002
#define BOLD_CHECK                      1003
#define ITALIC_CHECK                    1004
#define FONT_HEIGHT_COMBOBOX            1005
#define IDC_BACK_COLOR                  1006
#define VOLT_POR_DIV_COMBO              1007
#define IDC_SIGNAL_COLOR                1008
#define Bitmap2                         1010
#define IDC_OPEN_CLOSE                  1010
#define IDC_CLOSE                       1011
#define Bitmap3                         1011
#define IDC_GRAPH_NAME                  1012
#define IDC_OPEN_CLOSE2                 1013
#define LFC10_CONFIG                    11000
#define IDC_BITS                        11001
#define IDC_DATA                        11002
#define IDC_STOP                        11003
#define IDC_PARITY                      11004
#define IDC_PORT                        11005
#define IDC_SAMPLES_CANT                11008
#define IDC_PREV                        11010
#define IDC_NEXT                        11011
#define IDC_DEVICESTART                 11012
#define IDC_SHOW                        11013
#define IDC_GRAPH                       11014
#define IDC_EDGE_POS                    11015
#define IDC_FILTER                      11016
#define IDC_PORT_OPEN                   11017
#define IDC_PORT_CLOSE                  11018
#define IDC_PORT_APPLY                  11019
#define IDC_DEVICESTOP                  11020
#define IDC_BYTESIZE                    11021
#define IDC_STOPBITS                    11022
#define IDC_BAUDRATE                    11023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11007
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         11025
#define _APS_NEXT_SYMED_VALUE           11000
#endif
#endif
