// g30c02.cpp: implementation of the CBitmapWind class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "G30c02.h"

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

CBitmapWind::CBitmapWind()
{

}

CBitmapWind::~CBitmapWind()
{

}

DWORD CBitmapWind::StartGame()
{
	// Crear la ventana si no esta creada

	return 0;
}

DWORD CBitmapWind::Initialize()
{
	return 0;
}
