// g30c05.cpp: implementation of the CDXMaterial class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "g30c05.h"

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

CDXMaterial::CDXMaterial()
{
	Initialize();
}

CDXMaterial::~CDXMaterial()
{
	Release();
}

DWORD CDXMaterial::Initialize()
{
	return 0;
}

DWORD CDXMaterial::Release()
{
	return 0;
}
