//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DB11.rc
//
#define IDD_SQL_DLG                     1003
#define IDC_DATETIMEPICKER1             1021
#define IDC_DATETIMEPICKER2             1022
#define IDC_MUNICIPIO                   1028
#define IDC_SINDICATO                   1030
#define IDC_BNUMERO                     1032
#define IDC_BNOMBRE                     1033
#define IDC_B1APELLIDO                  1034
#define IDC_B2APELLIDO                  1035
#define IDC_BORGANISMO                  1036
#define IDC_BMUNICIPIO                  1037
#define IDC_BTEMA                       1038
#define IDC_BCLASIFICACION              1039
#define IDC_BDESDE                      1041
#define IDC_BHASTA                      1042
#define IDC_BSINDICATO                  1044
#define IDC_BORDENAR                    1047
#define IDC_NUMERO                      1048
#define IDC_NOMBRE                      1049
#define IDC_TEMA                        1054
#define IDC_TDEPARTAMENTO               1056
#define IDC_TSINDICATO                  1057
#define IDC_CLASIFICACION               1059
#define IDC_ORDENAR                     1060
#define IDC_BTPROVINCIA                 1061
#define IDC_BTDEPARTAMENTO              1062
#define IDC_BTSINDICATO                 1063
#define IDC_1APELLIDO                   1064
#define IDC_2APELLIDO                   1065
#define IDC_ORGANISMO                   1066
#define IDC_DESDE                       1067
#define IDC_HASTA                       1068
#define IDC_TPROVINCIA                  1069
#define IDC_CHECK1                      1071
#define IDC_CHECK2                      1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1004
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
