//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GLTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GLTEST_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       132
#define IDB_BITMAP1                     135
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_OPENGL                      1002
#define IDC_BORRARTODO                  1006
#define IDC_TREE_3DOBJECT               1011
#define IDC_READ3DS                     1012
#define IDB_BITMAP2                     12039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
