//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CT10.rc
//
#define IDD_CT10_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDC_RECEIVEDBYTESEDIT           1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON3                     1003
#define IDC_SEND                        1004
#define IDC_BUTTON4                     1005
#define IDC_BUTTON5                     1006
#define IDC_RECEIVEDBYTESCANT           1007
#define IDC_COMBO2                      1009
#define IDC_SENDMESSAGE                 1012
#define IDC_BUTTON6                     1013
#define IDC_SENTBYTESEDIT               1015
#define IDC_SENTBYTES                   1016
#define LFC10_CONFIG                    11000
#define IDC_BITS                        11001
#define IDC_DATA                        11002
#define IDC_STOP                        11003
#define IDC_PARITY                      11004
#define IDC_PORT                        11005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
