// Lester.h: interface for the CLester class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_LESTER_H__8FC3CE32_AEEE_11D3_A036_0000E8DE4B3B__INCLUDED_)
#define AFX_LESTER_H__8FC3CE32_AEEE_11D3_A036_0000E8DE4B3B__INCLUDED_

#include "Device.h"	// Added by ClassView
#include "grafsig.h"

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class AFX_EXT_CLASS CLester  
{
public:
	CDevice m_Device;
	CLester();
	virtual ~CLester();

};

#endif // !defined(AFX_LESTER_H__8FC3CE32_AEEE_11D3_A036_0000E8DE4B3B__INCLUDED_)
