//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by G3D.rc
//
#define IDC_G3D_BUTTON1                 5000
#define IDD_G3D_DIALOG1                 5000
#define IDD_G3D_DIALOG2                 5001
#define IDD_G3D_DIALOG3                 5002
#define IDI_G3D_ICON1                   5003
#define IDD_G3D_DIALOG4                 5004
#define IDD_G3D_DIALOG5                 5005
#define IDC_G3D_BUTTON3                 5007
#define IDD_G3D_DIALOG6                 5008
#define IDC_G3D_PAUSE                   5008
#define IDD_G3D_LEVEL1                  5009
#define IDC_G3D_FINISH                  5009
#define IDC_G3D_BUTTON4                 5014
#define IDC_G3D_BUTTON2                 5015
#define IDC_G3D_BUTTON5                 5016
#define IDC_G3D_BUTTON6                 5017
#define IDC_G3D_BUTTON9                 5018
#define IDC_G3D_BUTTON7                 5019
#define IDC_G3D_BUTTON8                 5020

#define IDC_G3D_EDIT1                   5021

#define IDC_G3D_EDIT2                   5022

#define IDC_G3D_RADIO1                  5025

#define IDC_G3D_RADIO2                  5026
#define IDC_G3D_ACIERTOS                5030
#define IDC_G3D_START                   5033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5010
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5034
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
