/*
 *   Copyright 2003-2004 The Apache Software Foundation.
// (c) Copyright IBM Corp. 2004, 2005 All Rights Reserved
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 */
#ifndef AXISUSERAPIARRAYS_INCLUDED
#define AXISUSERAPIARRAYS_INCLUDED

/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
/* NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE   */
/* ----------------------------------------------------------------   */
/* THIS HEADER FILE PATTERNED AFTER CORRESPONDING hpp HEADER FILE.    */
/* CHANGES TO hpp HEADER FILE MAY NEED TO BE PROPAGATED HERE AND IN   */
/* THE IMPLEMEMTATION OF THE C APIS.                                  */
/*                                                                    */
/* THIS FILE GENERATED BY CBINDINGGENERATOR TOOL.                     */
/* ----------------------------------------------------------------   */
/* NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE   */
/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */

#ifdef __cplusplus
 extern "C" {
#endif


#include <axis/GDefine.h>
#include <axis/TypeMapping.h>
#include <time.h>
#include <string.h>

/**
  * @file AxisUserAPIArrays.hpp
  * This file contains arrays defined for the basic types declared in AxisUserAPI.hpp
  * 
  * 
  */

#include <axis/AxisUserAPI.h>

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__duration_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__duration_Array(AXISCHANDLE xsd__duration_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__duration_Array(AXISCHANDLE xsd__duration_Array, xsdc__duration * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__duration * * axiscGetxsd__duration_Array(AXISCHANDLE xsd__duration_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__dateTime_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__dateTime_Array(AXISCHANDLE xsd__dateTime_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__dateTime_Array(AXISCHANDLE xsd__dateTime_Array, xsdc__dateTime * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__dateTime * * axiscGetxsd__dateTime_Array(AXISCHANDLE xsd__dateTime_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__time_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__time_Array(AXISCHANDLE xsd__time_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__time_Array(AXISCHANDLE xsd__time_Array, xsdc__time * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__time * * axiscGetxsd__time_Array(AXISCHANDLE xsd__time_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__date_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__date_Array(AXISCHANDLE xsd__date_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__date_Array(AXISCHANDLE xsd__date_Array, xsdc__date * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__date * * axiscGetxsd__date_Array(AXISCHANDLE xsd__date_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__gYearMonth_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__gYearMonth_Array(AXISCHANDLE xsd__gYearMonth_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__gYearMonth_Array(AXISCHANDLE xsd__gYearMonth_Array, xsdc__gYearMonth * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__gYearMonth * * axiscGetxsd__gYearMonth_Array(AXISCHANDLE xsd__gYearMonth_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__gYear_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__gYear_Array(AXISCHANDLE xsd__gYear_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__gYear_Array(AXISCHANDLE xsd__gYear_Array, xsdc__gYear * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__gYear * * axiscGetxsd__gYear_Array(AXISCHANDLE xsd__gYear_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__gMonthDay_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__gMonthDay_Array(AXISCHANDLE xsd__gMonthDay_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__gMonthDay_Array(AXISCHANDLE xsd__gMonthDay_Array, xsdc__gMonthDay * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__gMonthDay * * axiscGetxsd__gMonthDay_Array(AXISCHANDLE xsd__gMonthDay_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__gDay_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__gDay_Array(AXISCHANDLE xsd__gDay_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__gDay_Array(AXISCHANDLE xsd__gDay_Array, xsdc__gDay * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__gDay * * axiscGetxsd__gDay_Array(AXISCHANDLE xsd__gDay_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param orginal Axis_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__gMonth_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__gMonth_Array(AXISCHANDLE xsd__gMonth_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd_duration data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__gMonth_Array(AXISCHANDLE xsd__gMonth_Array, xsdc__gMonth * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd_duration data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__gMonth * * axiscGetxsd__gMonth_Array(AXISCHANDLE xsd__gMonth_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__string_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__string_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__string_Array(AXISCHANDLE xsd__string_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__string data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__string_Array(AXISCHANDLE xsd__string_Array, xsdc__string * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__string data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__string * axiscGetxsd__string_Array(AXISCHANDLE xsd__string_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__normalizedString_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__normalizedString_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__normalizedString_Array(AXISCHANDLE xsd__normalizedString_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__normalizedString data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__normalizedString_Array(AXISCHANDLE xsd__normalizedString_Array, xsdc__normalizedString * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__normalizedString data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__normalizedString * axiscGetxsd__normalizedString_Array(AXISCHANDLE xsd__normalizedString_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__token_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__token_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__token_Array(AXISCHANDLE xsd__token_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__token data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__token_Array(AXISCHANDLE xsd__token_Array, xsdc__token * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__token data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__token * axiscGetxsd__token_Array(AXISCHANDLE xsd__token_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__language_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__language_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__language_Array(AXISCHANDLE xsd__language_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__language data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__language_Array(AXISCHANDLE xsd__language_Array, xsdc__language * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__language data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__language * axiscGetxsd__language_Array(AXISCHANDLE xsd__language_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__Name_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__Name_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__Name_Array(AXISCHANDLE xsd__Name_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__Name data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__Name_Array(AXISCHANDLE xsd__Name_Array, xsdc__Name * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__Name data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__Name * axiscGetxsd__Name_Array(AXISCHANDLE xsd__Name_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__NCName_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__NCName_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__NCName_Array(AXISCHANDLE xsd__NCName_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__NCName data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__NCName_Array(AXISCHANDLE xsd__NCName_Array, xsdc__NCName * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__NCName data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__NCName * axiscGetxsd__NCName_Array(AXISCHANDLE xsd__NCName_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__ID_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__ID_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__ID_Array(AXISCHANDLE xsd__ID_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__ID data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__ID_Array(AXISCHANDLE xsd__ID_Array, xsdc__ID * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__ID data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__ID * axiscGetxsd__ID_Array(AXISCHANDLE xsd__ID_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__IDREF_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__IDREF_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__IDREF_Array(AXISCHANDLE xsd__IDREF_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__IDREF data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__IDREF_Array(AXISCHANDLE xsd__IDREF_Array, xsdc__IDREF * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__IDREF data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__IDREF * axiscGetxsd__IDREF_Array(AXISCHANDLE xsd__IDREF_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__IDREFS_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__IDREFS_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__IDREFS_Array(AXISCHANDLE xsd__IDREFS_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__IDREFS data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__IDREFS_Array(AXISCHANDLE xsd__IDREFS_Array, xsdc__IDREFS * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__IDREFS data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__IDREFS * axiscGetxsd__IDREFS_Array(AXISCHANDLE xsd__IDREFS_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__ENTITY_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__ENTITY_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__ENTITY_Array(AXISCHANDLE xsd__ENTITY_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__ENTITY data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__ENTITY_Array(AXISCHANDLE xsd__ENTITY_Array, xsdc__ENTITY * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__ENTITY data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__ENTITY * axiscGetxsd__ENTITY_Array(AXISCHANDLE xsd__ENTITY_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__ENTITIES_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__ENTITIES_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__ENTITIES_Array(AXISCHANDLE xsd__ENTITIES_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__ENTITIES data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__ENTITIES_Array(AXISCHANDLE xsd__ENTITIES_Array, xsdc__ENTITIES * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__ENTITIES data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__ENTITIES * axiscGetxsd__ENTITIES_Array(AXISCHANDLE xsd__ENTITIES_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__NMTOKEN_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__NMTOKEN_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__NMTOKEN_Array(AXISCHANDLE xsd__NMTOKEN_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__NMTOKEN data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__NMTOKEN_Array(AXISCHANDLE xsd__NMTOKEN_Array, xsdc__NMTOKEN * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__NMTOKEN data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__NMTOKEN * axiscGetxsd__NMTOKEN_Array(AXISCHANDLE xsd__NMTOKEN_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__NMTOKENS_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__NMTOKENS_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__NMTOKENS_Array(AXISCHANDLE xsd__NMTOKENS_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__NMTOKENS data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__NMTOKENS_Array(AXISCHANDLE xsd__NMTOKENS_Array, xsdc__NMTOKENS * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__NMTOKENS data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__NMTOKENS * axiscGetxsd__NMTOKENS_Array(AXISCHANDLE xsd__NMTOKENS_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__boolean_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__boolean_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__boolean_Array(AXISCHANDLE xsd__boolean_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__boolean data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__boolean_Array(AXISCHANDLE xsd__boolean_Array, xsdc__boolean * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__boolean data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__boolean * * axiscGetxsd__boolean_Array(AXISCHANDLE xsd__boolean_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__base64Binary_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__base64Binary_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__base64Binary_Array(AXISCHANDLE xsd__base64Binary_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__base64Binary data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__base64Binary_Array(AXISCHANDLE xsd__base64Binary_Array, xsdc__base64Binary * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__base64Binary data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__base64Binary * * axiscGetxsd__base64Binary_Array(AXISCHANDLE xsd__base64Binary_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__hexBinary_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__hexBinary_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__hexBinary_Array(AXISCHANDLE xsd__hexBinary_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__hexBinary data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__hexBinary_Array(AXISCHANDLE xsd__hexBinary_Array, xsdc__hexBinary * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__hexBinary data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__hexBinary * * axiscGetxsd__hexBinary_Array(AXISCHANDLE xsd__hexBinary_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__float_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__float_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__float_Array(AXISCHANDLE xsd__float_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__float data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__float_Array(AXISCHANDLE xsd__float_Array, xsdc__float * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__float data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__float * * axiscGetxsd__float_Array(AXISCHANDLE xsd__float_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__decimal_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__decimal_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__decimal_Array(AXISCHANDLE xsd__decimal_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__decimal data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__decimal_Array(AXISCHANDLE xsd__decimal_Array, xsdc__decimal * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__decimal data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__decimal * * axiscGetxsd__decimal_Array(AXISCHANDLE xsd__decimal_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__integer_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__integer_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__integer_Array(AXISCHANDLE xsd__integer_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__integer data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__integer_Array(AXISCHANDLE xsd__integer_Array, xsdc__integer * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__integer data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__integer * * axiscGetxsd__integer_Array(AXISCHANDLE xsd__integer_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__nonPositiveInteger_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__nonPositiveInteger_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__nonPositiveInteger_Array(AXISCHANDLE xsd__nonPositiveInteger_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__nonPositiveInteger data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__nonPositiveInteger_Array(AXISCHANDLE xsd__nonPositiveInteger_Array, xsdc__nonPositiveInteger * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__nonPositiveInteger data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__nonPositiveInteger * * axiscGetxsd__nonPositiveInteger_Array(AXISCHANDLE xsd__nonPositiveInteger_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__negativeInteger_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__negativeInteger_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__negativeInteger_Array(AXISCHANDLE xsd__negativeInteger_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__negativeInteger data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__negativeInteger_Array(AXISCHANDLE xsd__negativeInteger_Array, xsdc__negativeInteger * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__negativeInteger data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__negativeInteger * * axiscGetxsd__negativeInteger_Array(AXISCHANDLE xsd__negativeInteger_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__long_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__long_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__long_Array(AXISCHANDLE xsd__long_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__long data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__long_Array(AXISCHANDLE xsd__long_Array, xsdc__long * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__long data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__long * * axiscGetxsd__long_Array(AXISCHANDLE xsd__long_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__int_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__int_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__int_Array(AXISCHANDLE xsd__int_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__int data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__int_Array(AXISCHANDLE xsd__int_Array, xsdc__int * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__int data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__int * * axiscGetxsd__int_Array(AXISCHANDLE xsd__int_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__short_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__short_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__short_Array(AXISCHANDLE xsd__short_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__short data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__short_Array(AXISCHANDLE xsd__short_Array, xsdc__short * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__short data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__short * * axiscGetxsd__short_Array(AXISCHANDLE xsd__short_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__byte_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__byte_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__byte_Array(AXISCHANDLE xsd__byte_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__byte data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__byte_Array(AXISCHANDLE xsd__byte_Array, xsdc__byte * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__byte data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__byte * * axiscGetxsd__byte_Array(AXISCHANDLE xsd__byte_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__nonNegativeInteger_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__nonNegativeInteger_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__nonNegativeInteger_Array(AXISCHANDLE xsd__nonNegativeInteger_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__nonNegativeInteger data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__nonNegativeInteger_Array(AXISCHANDLE xsd__nonNegativeInteger_Array, xsdc__nonNegativeInteger * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__nonNegativeInteger data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__nonNegativeInteger * * axiscGetxsd__nonNegativeInteger_Array(AXISCHANDLE xsd__nonNegativeInteger_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__unsignedLong_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__unsignedLong_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__unsignedLong_Array(AXISCHANDLE xsd__unsignedLong_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__unsignedLong data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__unsignedLong_Array(AXISCHANDLE xsd__unsignedLong_Array, xsdc__unsignedLong * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__unsignedLong data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__unsignedLong * * axiscGetxsd__unsignedLong_Array(AXISCHANDLE xsd__unsignedLong_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__unsignedInt_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__unsignedInt_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__unsignedInt_Array(AXISCHANDLE xsd__unsignedInt_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__unsignedInt data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__unsignedInt_Array(AXISCHANDLE xsd__unsignedInt_Array, xsdc__unsignedInt * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__unsignedInt data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__unsignedInt * * axiscGetxsd__unsignedInt_Array(AXISCHANDLE xsd__unsignedInt_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__unsignedByte_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__unsignedByte_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__unsignedByte_Array(AXISCHANDLE xsd__unsignedByte_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__unsignedByte data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__unsignedByte_Array(AXISCHANDLE xsd__unsignedByte_Array, xsdc__unsignedByte * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__unsignedByte data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__unsignedByte * * axiscGetxsd__unsignedByte_Array(AXISCHANDLE xsd__unsignedByte_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__unsignedShort_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__unsignedShort_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__unsignedShort_Array(AXISCHANDLE xsd__unsignedShort_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__unsignedShort data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__unsignedShort_Array(AXISCHANDLE xsd__unsignedShort_Array, xsdc__unsignedShort * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__unsignedShort data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__unsignedShort * * axiscGetxsd__unsignedShort_Array(AXISCHANDLE xsd__unsignedShort_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__positiveInteger_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__positiveInteger_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__positiveInteger_Array(AXISCHANDLE xsd__positiveInteger_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__positiveInteger data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__positiveInteger_Array(AXISCHANDLE xsd__positiveInteger_Array, xsdc__positiveInteger * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__positiveInteger data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__positiveInteger * * axiscGetxsd__positiveInteger_Array(AXISCHANDLE xsd__positiveInteger_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__double_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__double_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__double_Array(AXISCHANDLE xsd__double_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__double data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__double_Array(AXISCHANDLE xsd__double_Array, xsdc__double * * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__double data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__double * * axiscGetxsd__double_Array(AXISCHANDLE xsd__double_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__anyURI_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__anyURI_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__anyURI_Array(AXISCHANDLE xsd__anyURI_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__anyURI data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__anyURI_Array(AXISCHANDLE xsd__anyURI_Array, xsdc__anyURI * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__anyURI data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__anyURI * axiscGetxsd__anyURI_Array(AXISCHANDLE xsd__anyURI_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__QName_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__QName_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__QName_Array(AXISCHANDLE xsd__QName_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__QName data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__QName_Array(AXISCHANDLE xsd__QName_Array, xsdc__QName * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__QName data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__QName * axiscGetxsd__QName_Array(AXISCHANDLE xsd__QName_Array, int * size);

/**
     * Constructor
     */

/**
     * Copy constructor
     * @param original xsd__NOTATION_Array to copy.
     */
AXISC_STORAGE_CLASS_INFO AXISCHANDLE axiscCreatexsd__NOTATION_Array(AXISCHANDLE original);

/**
     * Destructor
     */
AXISC_STORAGE_CLASS_INFO void axiscDestroyxsd__NOTATION_Array(AXISCHANDLE xsd__NOTATION_Array);

/**
     * Populate the array from a c-style array
     * 
     * @param array is a c-style array of pointers to the xsd__NOTATION data.
     * @param size of the array, including NULL entries.
     */
AXISC_STORAGE_CLASS_INFO void axiscSetxsd__NOTATION_Array(AXISCHANDLE xsd__NOTATION_Array, xsdc__NOTATION * array, 
	int size);

/**
     * Return a c-style array.
     * 
     * @param size, this will be updated with the size of the array returned.
     * @return c-style array of pointers to the xsd__NOTATION data.
     */
AXISC_STORAGE_CLASS_INFO const xsdc__NOTATION * axiscGetxsd__NOTATION_Array(AXISCHANDLE xsd__NOTATION_Array, int * size);


#ifdef __cplusplus
 }
#endif

#endif /* AXISUSERAPIARRAYS_INCLUDED */
