/* AUTOMATIC GENERATED HEADER DEFINITION */

#ifndef __ESS_RSSTYPES_H_
#define __ESS_RSSTYPES_H_


#define AE_RSS_TYPE_UNDEF	-1
#define AE_RSS_TYPE_RACF19	0
#define AE_RSS_TYPE_NOVELL3	1
#define AE_RSS_TYPE_SOLARIS24	2
#define AE_RSS_TYPE_HP_UX9	3
#define AE_RSS_TYPE_SUNOS	4
#define AE_RSS_TYPE_VMS	5
#define AE_RSS_TYPE_RACF21	6
#define AE_RSS_TYPE_NIS	7
#define AE_RSS_TYPE_AIX3	8
#define AE_RSS_TYPE_AIX4	9
#define AE_RSS_TYPE_SEOS	10
#define AE_RSS_TYPE_WINNT	11
#define AE_RSS_TYPE_RACF22	12
#define AE_RSS_TYPE_HP_UX10	13
#define AE_RSS_TYPE_SOLARIS25	14
#define AE_RSS_TYPE_NOVELL4	15
#define AE_RSS_TYPE_SYBASE	16
#define AE_RSS_TYPE_SAPR3	17
#define AE_RSS_TYPE_OS2	18
#define AE_RSS_TYPE_SOLARIS26	19
#define AE_RSS_TYPE_TSS44	20
#define AE_RSS_TYPE_TSS50	21
#define AE_RSS_TYPE_NOTES	22
#define AE_RSS_TYPE_ORACLE	23
#define AE_RSS_TYPE_ACF2_61	25
#define AE_RSS_TYPE_NCR3	26
#define AE_RSS_TYPE_PROXIMA_SSO	27
#define AE_RSS_TYPE_SEOS2	28
#define AE_RSS_TYPE_AIX42	29
#define AE_RSS_TYPE_RACF23	31
#define AE_RSS_TYPE_ACF2_62	32
#define AE_RSS_TYPE_AS400	33
#define AE_RSS_TYPE_API3270	34
#define AE_RSS_TYPE_RACF24	35
#define AE_RSS_TYPE_RACF25	36
#define AE_RSS_TYPE_EXCHANGE	37
#define AE_RSS_TYPE_OSF1	38
#define AE_RSS_TYPE_ESS_ADMIN	39
#define AE_RSS_TYPE_NOVELL5	40
#define AE_RSS_TYPE_NETSCAPE	41
#define AE_RSS_TYPE_RACF26	42
#define AE_RSS_TYPE_SAFEGUARD	43
#define AE_RSS_TYPE_IRIX	44
#define AE_RSS_TYPE_WIN2000	47
#define AE_RSS_TYPE_RACF	52
#define AE_RSS_TYPE_WINLOCAL	60
#define AE_RSS_TYPE_ALL	99
#define AE_RSS_TYPE_OGENCS	100
#define AE_RSS_TYPE_LDAP	102
#define AE_RSS_TYPE_NAVIRADIUS	103
#define AE_RSS_TYPE_APPLIX	152
#define AE_RSS_TYPE_MAUI	162
#define AE_RSS_TYPE_MAUI2	163
#define AE_RSS_TYPE_APLE	166
#define AE_RSS_TYPE_UWEB	167
#define AE_RSS_TYPE_TEXAS	169
#define AE_RSS_TYPE_SICO	170
#define AE_RSS_TYPE_ACCEZANNE	208
#define AE_RSS_TYPE_PRLSOFT	209
#define AE_RSS_TYPE_APDS	210
#define AE_RSS_TYPE_SCE	211
#define AE_RSS_TYPE_CEPR	212
#define AE_RSS_TYPE_LDAP_BS	213
#define AE_RSS_TYPE_RRMMONLINE	215
#define AE_RSS_TYPE_PLAD	216
#define AE_RSS_TYPE_TDB_JAVA	217
#define AE_RSS_TYPE_HIS_EDOCTOR	218
#define AE_RSS_TYPE_SINGER	220
#define AE_RSS_TYPE_OPERACIONAL	221
#define AE_RSS_TYPE_NOTESDB	227

#endif
