//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VLClient1.rc
//
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_VLCLIENT1_FORM              101
#define IDP_FAILED_TO_CREATE            102
#define IDR_MAINFRAME                   128
#define IDR_VLCLIETYPE                  129
#define IDI_ICON1                       130
#define IDC_CONECT                      1000
#define IDC_LINES                       1001
#define IDC_CANT                        1002
#define IDC_STATUS                      1003
#define IDC_Request_Chat                1004
#define IDC_Nick                        1005
#define IDC_USERS_LIST                  1008
#define IDC_PUBLIC_LIST                 1009
#define IDC_Public                      1010
#define IDC_Ignore                      1011
#define IDC_SEND_PUBLIC                 1016
#define IDC_FINISH_CHAT                 1017
#define IDC_Finish_Video                1018
#define IDC_OPENGL                      1019
#define IDC_COORDENADA_X                1020
#define IDC_COORDENADA_Z                1021
#define IDC_VALUE                       1022
#define IDC_Get_Ficha                   1023
#define IDC_SIMULATION                  1024
#define IDC_IPADDRESS1                  1025
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
